apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsotelapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejsotelapp
  template:
    metadata:
      labels:
        app: nodejsotelapp
    spec:
      containers:
      - name: nodejsotelapp
        image: docker.io/dpacheconr/nodejsotelapp:1.0.0 # update with your app image name
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://otel-collector.default.svc.cluster.local:4318
          - name: OTEL_SERVICE_NAME_NODE
            value: nodejsappdemootelcollector
---
apiVersion: v1
kind: Service
metadata:
  name: nodejsotelapp
spec:
  selector:
    app.kubernetes.io/name: nodejsotelapp
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8080