apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsotelapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejsotelapp
  template:
    metadata:
      labels:
        app: nodejsotelapp
    spec:
      containers:
      - name: nodejsotelapp
        image: docker.io/dpacheconr/nodejsotelapp:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://otel-collector.default.svc.cluster.local:4318
